- README.md
Page not found
Oops! The URL you're looking for doesn't exist on our server.
> remove video url

- README.md
I created this comparison of application file structures between some of the most respected Angular authorities.
> Link to expert file structure comparison

- README.md
> remove "Example Cases of AngularJS" video

- README.md
Added [A Primer on Testing AngularJS Applications] (http://payworksmobile.com/blog/2015/03/05/a-primer-on-testing-angularjs-applications/). I added it to the top of the list because like the name implies it is a somewhat high level intro. But I can switch  the ordering of course.
Great collection of resources, thanks for that!
> Added 'A Primer on Testing AngularJS Applications' resource

- README.md
MWS features Angular, Karma, and Gulp integration
> Added link to my modern web seed project

- README.md
New introductory book from Addison Wesley on AngularJs.
http://www.pearsoned.co.uk/bookshop/detail.asp?item=100000000595964
> Add Dayley book

- README.md
> Added AngularJS by Example book reference.

- README.md
A Preview of Angular 2 and TypeScript in Visual Studio
> Add a general topic Angular 2 and TypeScript in Visual Studio

- README.md
I hope I am doing the pull request the right way. If not please suggest the procedure.
> Fixed link in UI stuff sub topic

- README.md
Shameless plug here, adding my own project to the list :)
> Add loopback-angular-admin

- README.md
Hi, I found there are some interesting tutorial series on Codementor, and thus I'd like to add them into the list.
I added some other non-series but related topics I found on Codementor as well.
How do you think?
Thanks.
> Add a "tutorial series"

- README.md
Add link to http://teropa.info/blog/2015/06/09/transclusion.html
> Add link to new transclusion guide

- README.md
Well, I guess my book also have a place in this list :)
> Add "Deep Dive Into Angular.js directives"

- README.md
Hi, I added my newly released AgularJS course on Udemy. The attached link is a coupon with 86% off discount. Let me know if something's wrong so I can correct it
Thanks.
> New AngularJS Course

- README.md
ng-inspector is really useful extension for Chrome, so I guess it will be good addition to dev tools section.
> Added ng-inspector in development tools

- README.md
Added a usefull link.
Not sure if is the best location.
Let me know
> added todd motto's post on ngmodel options and digest cycle

- README.md
Added codedamn's Angular JS tutorials which explains the fundamentals in a clear and concise manner.
> Add new source in video section

- README.md
Added "Boost the Performance of an AngularJS Application Using Immutable Data" : http://blog.mgechev.com/2015/03/02/immutability-in-angularjs-immutablejs
> Added "Boost the Performance of an AngularJS Application Using Immutable Data

- README.md
For applications that use/require pagination, the links added can be very helpful for a quick implementation.
> Updated README.md with useful pagination links under UI Stuff section

- README.md
This adds a new entry [Single Page Web Applications with AngularJS](https://www.coursera.org/learn/single-page-web-apps-with-angularjs) to the Courses section.
> Add a course hosted on Coursera.org
